name: Revalidate Changed Articles

on:
  push:
    branches: [main]
    paths:
      - 'app/thoughts/_articles/**/*.md'
      - 'app/thoughts/_articles/**/*.mdx'

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: app/thoughts/_articles/**/*.{md,mdx}

      - name: Revalidate changed articles
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          REVALIDATION_TOKEN: ${{ secrets.REVALIDATION_TOKEN }}
          VERCEL_DOMAIN: ${{ secrets.VERCEL_DOMAIN }}
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          paths_to_revalidate=""
          
          for file in $changed_files; do
            echo "Processing: $file"
            filename=$(basename "$file")
            slug="${filename%.*}"
            paths_to_revalidate="$paths_to_revalidate,\"/thoughts/$slug\""
          done
          
          # Always revalidate the thoughts index page
          paths_to_revalidate="$paths_to_revalidate,\"/thoughts\""
          
          # Format as JSON array
          paths_to_revalidate="[${paths_to_revalidate#,}]"
          
          echo "Revalidating paths: $paths_to_revalidate"
          
          # Fixed curl command with proper URL formatting
          curl -X POST "https://${VERCEL_DOMAIN}/api/revalidate" \
            -H "Authorization: Bearer ${REVALIDATION_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"paths\": $paths_to_revalidate}" \
            --fail --show-error